### ISSUE TITLE
keepWhen vs. sampleWhen

### ISSUE THREAD

**Issue by rgrempel** [Apanatshka/elm-signal-extra#18]
I happened to be reading through `keepWhen` and `sampleWhen`, and was wondering if they might be reversed? Now, I may just be imagining things, but here's the code:

``` elm
{-| The good old `keepWhen` filter that keeps events from the `Signal a` as long as the
`Signal Bool` is true. 
-}
keepWhen : Signal Bool -> a -> Signal a -> Signal a
keepWhen boolSig a aSig =
  zip boolSig aSig
  |> sampleOn aSig
  |> keepIf fst (True, a)
  |> map snd

{-| A combination of `Signal.sampleOn` and `keepWhen`. When the
first signal becomes `True`, the most recent value of the second signal
will be propagated.  
[Before Elm 0.12](
https://github.com/elm-lang/elm-compiler/blob/master/changelog.md#012)
 this was the standard behaviour of `keepWhen`.
-}
sampleWhen : Signal Bool -> a -> Signal a -> Signal a
sampleWhen bs def sig =
  zip bs sig
  |> keepIf fst (True, def)
  |> map snd
```

To my eye, they look equivalent, except that `keepWhen` uses `sampleOn`, and `sampleWhen` does not. At least on the surface, that seems backwards -- it seems as though `sampleWhen` ought to use `sampleOn`.

But I haven't really thought this through very deeply, so I might be imagining things.

**Comment by Apanatshka** [comment]
This is one of those `Signal` is both a time-varying-value and event-stream distinctions. And as it turned out, the event-stream view of things won, because at that time filter was used before sending something into a `foldp`, and `foldp` makes events explicit. 

So the idea is: `keepWhen` is the event-based view where the value signal (the one being filtered) has "update" events which are only let through when the boolean signal is true. So the events from the boolean signal **don't** influence the output events directly. 
On the other side you have `sampleWhen`, which is the value-based view that when the boolean signal is false, the output signal is kept constant (latest value of the value signal), but when the boolean signal becomes true the output signal updates the latest value of the value signal. If you look at this behaviour from an event-based point of view, the `sampleWhen` samples the value signal when the boolean signal becomes true. The "update" events on the output signal are not guaranteed to originate from the value signal. 

[See also](https://groups.google.com/d/topic/elm-discuss/mLFNZ4j057w/discussion) [marble diagrams](http://share-elm.com/sprout/55d53a1ee4b06aacf0e8c175/0.12.3/view) I made of this stuff shortly after the behaviour of the then built-in `keepWhen` was switched from the value-based view (`sampleWhen`) to the event-based view (`keepWhen` as defined in this lib).

**Comment by rgrempel** [comment]
Ah, that make sense -- thanks!
